version: 2

project_name: qvm

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true
    name_template: 'qvm'

archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

brews:
  - repository:
      owner: dpastoor
      name: homebrew-tap
    directory: Formula
    test: |
      system "#{bin}/qvm -v"
    install: |-
      bin.install "qvm"
      bash_completion.install "completions/qvm.bash" => "qvm"
      zsh_completion.install "completions/qvm.zsh" => "_qvm"
      fish_completion.install "completions/qvm.fish"
      man1.install "manpages/qvm.1.gz"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
  footer: |
    ## Installation Instructions
    ### Mac
    first time:
    ```
    brew install dpastoor/tap/qvm
    ```
    upgrade:
    ```
    brew upgrade qvm
    ```
    ### Linux
    ```
    sudo wget https://github.com/dpastoor/qvm/releases/download/{{ .Tag }}/qvm_linux_amd64.tar.gz -O /tmp/qvm.tar.gz
    sudo tar xzf /tmp/qvm.tar.gz qvm
    sudo mv qvm /usr/local/bin/qvm
    sudo chmod +x /usr/local/bin/qvm
    ```

    ### Linux User

    Assumes `~/bin` is available in your PATH

    ```
    wget https://github.com/dpastoor/qvm/releases/download/{{ .Tag }}/qvm_linux_amd64.tar.gz -O /tmp/qvm.tar.gz
    tar xzf /tmp/qvm.tar.gz qvm
    mv qvm ~/bin/qvm
    chmod +x ~/bin/qvm
    ```

snapshot:
  version_template: '{{ incpatch .Version }}-next'