# https://taskfile.dev

version: '3'

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org,direct

vars:
  DOCKER: '{{default "docker" .DOCKER}}'

tasks:
  run:
    desc: Run the binary
    cmds:
    ## task run -- api would be equivalent of go run main.go api
      - go run main.go {{.CLI_ARGS}} 
  dev:
    desc: Setup git hooks
    cmds:
      - cp -f scripts/pre-commit.sh .git/hooks/pre-commit

  setup:
    desc: Install dependencies
    cmds:
      - go mod tidy

  build:
    desc: Build the binary
    sources:
      - ./**/*.go
    generates:
      - ./qvm
    cmds:
      - go build

  test:
    desc: Run tests
    env:
      LC_ALL: C
    vars:
      TEST_OPTIONS: '{{default "" .TEST_OPTIONS}}'
      SOURCE_FILES: '{{default "./..." .SOURCE_FILES}}'
      TEST_PATTERN: '{{default "." .TEST_PATTERN}}'
    cmds:
      - go test {{.TEST_OPTIONS}} -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt {{.SOURCE_FILES}} -run {{.TEST_PATTERN}} -timeout=5m

  cover:
    desc: Open the cover tool
    cmds:
      - go tool cover -html=coverage.txt

  fmt:
    desc: gofumpt all code
    cmds:
      - gofumpt -w -l .

  lint:
    desc: Lint the code with golangci-lint
    cmds:
      - golangci-lint run ./...

  ci:
    desc: Run all CI steps
    cmds:
      - task: setup
      - task: build
      - task: test

  default:
    desc: Runs the default tasks
    cmds:
      - task: ci

  release:
    desc: Create a new tag
    vars:
      NEXT:
      # https://github.com/caarlos0/svu
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin --tags

  qvm:test:pkg:
    desc: Test a package
    cmds:
      - docker run --platform linux/{{.Platform}} --rm --workdir /tmp -v $PWD/dist:/tmp {{.Image}} sh -c '{{.Cmd}} && qvm --version'

  qvm:test:rpm:
    desc: Tests rpm packages
    vars:
      rpm: 'rpm --nodeps -ivh'
    cmds:
      - task: qvm:test:pkg
        vars:
          Platform: 'amd64'
          Image: fedora
          Cmd: '{{.rpm}} qvm-*.x86_64.rpm'
      # - task: qvm:test:pkg
      #   vars:
      #     Platform: 'arm64'
      #     Image: fedora
      #     Cmd: '{{.rpm}} qvm-*.aarch64.rpm'
      # - task: qvm:test:pkg
      #   vars:
      #     Platform: 'arm/7'
      #     Image: fedora
      #     Cmd: '{{.rpm}} qvm-*.armv7hl.rpm'

  qvm:test:deb:
    desc: Tests deb packages
    vars:
      dpkg: 'dpkg -i'
    cmds:
      - task: qvm:test:pkg
        vars:
          Platform: 'amd64'
          Image: ubuntu
          Cmd: '{{.dpkg}} qvm*_amd64.deb'
      # - task: qvm:test:pkg
      #   vars:
      #     Platform: 'arm64'
      #     Image: ubuntu
      #     Cmd: '{{.dpkg}} qvm*_arm64.deb'
      # - task: qvm:test:pkg
      #   vars:
      #     Platform: 'arm/7'
      #     Image: ubuntu
      #     Cmd: '{{.dpkg}} qvm*_armhf.deb'

  qvm:test:apk:
    desc: Tests apk packages
    vars:
      apk: 'apk add --allow-untrusted -U'
    cmds:
      - task: qvm:test:pkg
        vars:
          Platform: 'amd64'
          Image: alpine
          Cmd: '{{.apk}} qvm*_x86_64.apk'
      # - task: qvm:test:pkg
      #   vars:
      #     Platform: 'arm64'
      #     Image: alpine
      #     Cmd: '{{.apk}} qvm*_aarch64.apk'
      # - task: qvm:test:pkg
      #   vars:
      #     Platform: 'arm/7'
      #     Image: alpine
      #     Cmd: '{{.apk}} qvm*_armv7.apk'

  qvm:test:
    desc: Test built linux packages
    cmds:
      - task: qvm:test:apk
      - task: qvm:test:deb
      - task: qvm:test:rpm

  goreleaser:
    desc: Run GoReleaser either in snapshot or release mode
    deps:
      - build
    vars:
      SNAPSHOT:
        sh: 'if [[ $GITHUB_REF != refs/tags/v* ]]; then echo "--snapshot"; fi'
    cmds:
      - goreleaser release --rm-dist {{.SNAPSHOT}}
